import {ProductImage, productImages} from "./product-image.model";
import {ProductDetail, productDetails} from "./product-detail.model";
import {ProductType, productTypes} from "./product-type.model";
import {Brand, brands} from "./brand.model";


export class Product {
  id: number
  name: string
  color: string
  gender: string
  type: ProductType
  brand: Brand
  description: string
  image: ProductImage | undefined
  productDetails: ProductDetail[]
  active: boolean

  constructor(id: number, name: string, color: string, gender: string, type: ProductType, brand: Brand, description: string, image: ProductImage, productDetails: ProductDetail[], active: boolean) {
    this.id = id
    this.name = name
    this.color = color
    this.type = type
    this.brand = brand
    this.description = description
    this.image = image
    this.productDetails = productDetails
    this.active = active
  }
}

export let products: Product[] =
  [
    {
      "id": 1,
      "name": "Giày Thể Thao Nam Biti's Hunter",
      "color": "Xám",
      "type": productTypes[0],
      "gender": "Male",
      "brand": brands[0],
      "image": productImages.find(image => image.productDetailId === 1),
      "productDetails": productDetails.filter(detail => detail.productId ===1),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 2,
      "name": "Giày Thể Thao Nam Biti's Hunter",
      "color": "Đen",
      "type": productTypes[0],
      "gender": "Male",
      "brand": brands[0],
      "image": productImages.find(image => image.productDetailId ===6),
      "productDetails": productDetails.filter(detail => detail.productId ===2),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 3,
      "name": "Giày Thể Thao Nam Biti's Hunter",
      "color": "Trắng",
      "type": productTypes[0],
      "gender": "Male",
      "brand": brands[0],
      "image": productImages.find(image => image.productDetailId ===11),
      "productDetails": productDetails.filter(detail => detail.productId ===3),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 4,
      "name": "Giày Thể Thao Nam Biti's Hunter Core",
      "color": "Đen",
      "type": productTypes[0],
      "gender": "Male",
      "brand": brands[0],
      "image": productImages.find(image => image.productDetailId ===16),
      "productDetails": productDetails.filter(detail => detail.productId ===4),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 5,
      "name": "Giày Thể Thao Nam Biti's Hunter Core",
      "color": "Xám",
      "type": productTypes[0],
      "gender": "Male",
      "brand": brands[0],
      "image": productImages.find(image => image.productDetailId ===21),
      "productDetails": productDetails.filter(detail => detail.productId ===5),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 6,
      "name": "Giày Thể Thao Nam Biti's Hunter Core",
      "color": "Xanh",
      "type": productTypes[0],
      "gender": "Male",
      "brand": brands[0],
      "image": productImages.find(image => image.productDetailId ===26),
      "productDetails": productDetails.filter(detail => detail.productId ===6),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 7,
      "name": "Giày Thể Thao Nam Biti's Hunter X LITEPLEX",
      "color": "Đen",
      "type": productTypes[0],
      "gender": "Male",
      "brand": brands[0],
      "image": productImages.find(image => image.productDetailId ===31),
      "productDetails": productDetails.filter(detail => detail.productId ===7),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 8,
      "name": "Giày Thể Thao Nam Biti's Hunter X LITEPLEX",
      "color": "Rêu",
      "type": productTypes[0],
      "gender": "Male",
      "brand": brands[0],
      "image": productImages.find(image => image.productDetailId ===36),
      "productDetails": productDetails.filter(detail => detail.productId ===8),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 9,
      "name": "Giày Thể Thao Nam Biti's Hunter X LITEPLEX",
      "color": "Kem",
      "type": productTypes[0],
      "gender": "Male",
      "brand": brands[0],
      "image": productImages.find(image => image.productDetailId ===41),
      "productDetails": productDetails.filter(detail => detail.productId ===9),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 10,
      "name": "Giày Thể Thao Nam Hunter Street",
      "color": "Xanh",
      "type": productTypes[0],
      "gender": "Male",
      "brand": brands[0],
      "image": productImages.find(image => image.productDetailId ===46),
      "productDetails": productDetails.filter(detail => detail.productId ===10),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 11,
      "name": "Giày Thể Thao Nam Hunter Street",
      "color": "Xám",
      "type": productTypes[0],
      "gender": "Male",
      "brand": brands[0],
      "image": productImages.find(image => image.productDetailId ===51),
      "productDetails": productDetails.filter(detail => detail.productId ===11),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 12,
      "name": "Giày Thể Thao Nam Hunter Street",
      "color": "Cam",
      "type": productTypes[0],
      "gender": "Male",
      "brand": brands[0],
      "image": productImages.find(image => image.productDetailId ===56),
      "productDetails": productDetails.filter(detail => detail.productId ===12),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 13,
      "name": "Giày Thể Thao Nam Biti's Hunter Core 3D-Airmesh",
      "color": "Đen",
      "type": productTypes[0],
      "gender": "Male",
      "brand": brands[0],
      "image": productImages.find(image => image.productDetailId ===61),
      "productDetails": productDetails.filter(detail => detail.productId ===13),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 14,
      "name": "Giày Thể Thao Nam Biti's Hunter Core 3D-Airmesh",
      "color": "Xám",
      "type": productTypes[0],
      "gender": "Male",
      "brand": brands[0],
      "image": productImages.find(image => image.productDetailId ===66),
      "productDetails": productDetails.filter(detail => detail.productId ===14),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 15,
      "name": "Giày Thể Thao Nam Biti's Hunter X Midnight EZ-STRAP",
      "color": "Đen",
      "type": productTypes[0],
      "gender": "Male",
      "brand": brands[0],
      "image": productImages.find(image => image.productDetailId ===71),
      "productDetails": productDetails.filter(detail => detail.productId ===15),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 16,
      "name": "Giày Thể Thao Nam Biti's Hunter Core Refreshing Collection",
      "color": "Đen",
      "type": productTypes[0],
      "gender": "Male",
      "brand": brands[0],
      "image": productImages.find(image => image.productDetailId ===76),
      "productDetails": productDetails.filter(detail => detail.productId ===16),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 17,
      "name": "Giày Thể Thao Nam Biti's Hunter Core Refreshing Collection",
      "color": "Trắng",
      "type": productTypes[0],
      "gender": "Male",
      "brand": brands[0],
      "image": productImages.find(image => image.productDetailId ===81),
      "productDetails": productDetails.filter(detail => detail.productId ===17),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 18,
      "name": "Giày Thể Thao Nam Biti's Hunter Street Ver 2",
      "color": "Trắng",
      "type": productTypes[0],
      "gender": "Male",
      "brand": brands[0],
      "image": productImages.find(image => image.productDetailId ===86),
      "productDetails": productDetails.filter(detail => detail.productId ===18),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 19,
      "name": "Giày Thể Thao Nam Biti's Hunter Street Ver 2",
      "color": "Đen",
      "type": productTypes[0],
      "gender": "Male",
      "brand": brands[0],
      "image": productImages.find(image => image.productDetailId ===91),
      "productDetails": productDetails.filter(detail => detail.productId ===19),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 20,
      "name": "Giày Thể Thao Nam Biti's Hunter Midnight 2",
      "color": "Đen",
      "type": productTypes[0],
      "gender": "Male",
      "brand": brands[0],
      "image": productImages.find(image => image.productDetailId ===96),
      "productDetails": productDetails.filter(detail => detail.productId ===20),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 21,
      "name": "Giày Bóng Đá Nam Biti's Hunter Football",
      "color": "Đỏ",
      "type": productTypes[1],
      "gender": "Male",
      "brand": brands[0],
      "image": productImages.find(image => image.productDetailId ===101),
      "productDetails": productDetails.filter(detail => detail.productId ===21),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 22,
      "name": "Giày Bóng Đá Nam Biti's Hunter Football",
      "color": "Xanh",
      "type": productTypes[1],
      "gender": "Male",
      "brand": brands[0],
      "image": productImages.find(image => image.productDetailId ===106),
      "productDetails": productDetails.filter(detail => detail.productId ===22),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 23,
      "name": "Giày Bóng Đá Nam Biti's Hunter Football",
      "color": "Cam",
      "type": productTypes[1],
      "gender": "Male",
      "brand": brands[0],
      "image": productImages.find(image => image.productDetailId ===111),
      "productDetails": productDetails.filter(detail => detail.productId ===23),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 24,
      "name": "Giày Bóng Đá Nam Biti's Hunter Football Futsal",
      "color": "Xanh",
      "type": productTypes[1],
      "gender": "Male",
      "brand": brands[0],
      "image": productImages.find(image => image.productDetailId ===116),
      "productDetails": productDetails.filter(detail => detail.productId ===24),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 25,
      "name": "Giày Bóng Đá Nam Biti's Hunter Football Futsal",
      "color": "Đen",
      "type": productTypes[1],
      "gender": "Male",
      "brand": brands[0],
      "image": productImages.find(image => image.productDetailId ===121),
      "productDetails": productDetails.filter(detail => detail.productId ===25),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 26,
      "name": "Giày Bóng Đá Nam Biti's Hunter Football Futsal",
      "color": "Trắng",
      "type": productTypes[1],
      "gender": "Male",
      "brand": brands[0],
      "image": productImages.find(image => image.productDetailId ===126),
      "productDetails": productDetails.filter(detail => detail.productId ===26),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 27,
      "name": "Giày Sandal Nam",
      "color": "Nâu",
      "type": productTypes[2],
      "gender": "Male",
      "brand": brands[0],
      "image": productImages.find(image => image.productDetailId ===131),
      "productDetails": productDetails.filter(detail => detail.productId ===27),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 28,
      "name": "Giày Sandal Nam",
      "color": "Đen",
      "type": productTypes[2],
      "gender": "Male",
      "brand": brands[0],
      "image": productImages.find(image => image.productDetailId ===136),
      "productDetails": productDetails.filter(detail => detail.productId ===28),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 29,
      "name": "Giày Sandal Nam Eva Phun Biti's Hunter",
      "color": "Xám",
      "type": productTypes[2],
      "gender": "Male",
      "brand": brands[0],
      "image": productImages.find(image => image.productDetailId ===141),
      "productDetails": productDetails.filter(detail => detail.productId ===29),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 30,
      "name": "Giày Sandal Nam Eva Phun Biti's Hunter",
      "color": "Đen",
      "type": productTypes[2],
      "gender": "Male",
      "brand": brands[0],
      "image": productImages.find(image => image.productDetailId ===146),
      "productDetails": productDetails.filter(detail => detail.productId ===30),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 31,
      "name": "Giày Sandal Nam Eva Phun Biti's Hunter",
      "color": "Rêu",
      "type": productTypes[2],
      "gender": "Male",
      "brand": brands[0],
      "image": productImages.find(image => image.productDetailId ===151),
      "productDetails": productDetails.filter(detail => detail.productId ===31),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 32,
      "name": "Giày Da Nam Biti's X",
      "color": "Vàng",
      "type": productTypes[3],
      "gender": "Male",
      "brand": brands[0],
      "image": productImages.find(image => image.productDetailId ===156),
      "productDetails": productDetails.filter(detail => detail.productId ===32),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 33,
      "name": "Giày Da Nam Biti's X",
      "color": "Đen",
      "type": productTypes[3],
      "gender": "Male",
      "brand": brands[0],
      "image": productImages.find(image => image.productDetailId ===161),
      "productDetails": productDetails.filter(detail => detail.productId ===33),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 34,
      "name": "Giày Da Nam Biti's X",
      "color": "Đen",
      "type": productTypes[3],
      "gender": "Male",
      "brand": brands[0],
      "image": productImages.find(image => image.productDetailId ===166),
      "productDetails": productDetails.filter(detail => detail.productId ===34),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 35,
      "name": "Giày Da Nam Biti's X",
      "color": "Vàng",
      "type": productTypes[3],
      "gender": "Male",
      "brand": brands[0],
      "image": productImages.find(image => image.productDetailId ===171),
      "productDetails": productDetails.filter(detail => detail.productId ===35),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 36,
      "name": "Giày Da Nam Biti's X",
      "color": "Nâu",
      "type": productTypes[3],
      "gender": "Male",
      "brand": brands[0],
      "image": productImages.find(image => image.productDetailId ===176),
      "productDetails": productDetails.filter(detail => detail.productId ===36),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 37,
      "name": "Giày Da Nam Biti's X",
      "color": "Đen",
      "type": productTypes[3],
      "gender": "Male",
      "brand": brands[0],
      "image": productImages.find(image => image.productDetailId ===181),
      "productDetails": productDetails.filter(detail => detail.productId ===37),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 38,
      "name": "Giày Thể Thao Nam Paris Low Top Trainers",
      "color": "Xanh",
      "type": productTypes[0],
      "gender": "Male",
      "brand": brands[2],
      "image": productImages.find(image => image.productDetailId ===186),
      "productDetails": productDetails.filter(detail => detail.productId ===38),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 39,
      "name": "Giày Thể Thao Nam Runner Trainers",
      "color": "Xanh",
      "type": productTypes[0],
      "gender": "Male",
      "brand": brands[2],
      "image": productImages.find(image => image.productDetailId ===191),
      "productDetails": productDetails.filter(detail => detail.productId ===39),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 40,
      "name": "Giày Thể Thao Nam Runner Trainers",
      "color": "Đen",
      "type": productTypes[0],
      "gender": "Male",
      "brand": brands[2],
      "image": productImages.find(image => image.productDetailId ===196),
      "productDetails": productDetails.filter(detail => detail.productId ===40),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 41,
      "name": "Giày Thể Thao Nam Runner Trainers",
      "color": "Đỏ",
      "type": productTypes[0],
      "gender": "Male",
      "brand": brands[2],
      "image": productImages.find(image => image.productDetailId ===201),
      "productDetails": productDetails.filter(detail => detail.productId ===41),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 42,
      "name": "Giày Thể Thao Nam Runner Trainers",
      "color": "Trắng",
      "type": productTypes[0],
      "gender": "Male",
      "brand": brands[2],
      "image": productImages.find(image => image.productDetailId ===206),
      "productDetails": productDetails.filter(detail => detail.productId ===42),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 43,
      "name": "Giày Thể Thao Nam Triple S Trainers",
      "color": "Đen",
      "type": productTypes[0],
      "gender": "Male",
      "brand": brands[2],
      "image": productImages.find(image => image.productDetailId ===211),
      "productDetails": productDetails.filter(detail => detail.productId ===43),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 44,
      "name": "Giày Thể Thao Nam Nike Air Force",
      "color": "Trắng ",
      "type": productTypes[0],
      "gender": "Male",
      "brand": brands[1],
      "image": productImages.find(image => image.productDetailId ===216),
      "productDetails": productDetails.filter(detail => detail.productId ===44),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 45,
      "name": "Giày Cơ Bản Nam Nike Air Force",
      "color": "Đen",
      "type": productTypes[4],
      "gender": "Male",
      "brand": brands[1],
      "image": productImages.find(image => image.productDetailId ===221),
      "productDetails": productDetails.filter(detail => detail.productId ===45),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 46,
      "name": "Giày Cơ Bản Nam Nike Air Force",
      "color": "Xanh",
      "type": productTypes[4],
      "gender": "Male",
      "brand": brands[1],
      "image": productImages.find(image => image.productDetailId ===226),
      "productDetails": productDetails.filter(detail => detail.productId ===46),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 47,
      "name": "Giày Cơ Bản Nam Nike Air Force",
      "color": "Trắng ",
      "type": productTypes[4],
      "gender": "Male",
      "brand": brands[1],
      "image": productImages.find(image => image.productDetailId ===231),
      "productDetails": productDetails.filter(detail => detail.productId ===47),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 48,
      "name": "Giày Cơ Bản Nam Nike Air Force",
      "color": "Đỏ",
      "type": productTypes[4],
      "gender": "Male",
      "brand": brands[1],
      "image": productImages.find(image => image.productDetailId ===236),
      "productDetails": productDetails.filter(detail => detail.productId ===48),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 49,
      "name": "Giày Cơ Bản Nam Nike Air Force",
      "color": "Xanh",
      "type": productTypes[4],
      "gender": "Male",
      "brand": brands[1],
      "image": productImages.find(image => image.productDetailId ===241),
      "productDetails": productDetails.filter(detail => detail.productId ===49),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 50,
      "name": "Giày Cơ Bản Nam Nike Air Force",
      "color": "Xám",
      "type": productTypes[4],
      "gender": "Male",
      "brand": brands[1],
      "image": productImages.find(image => image.productDetailId ===246),
      "productDetails": productDetails.filter(detail => detail.productId ===50),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 51,
      "name": "Giày Cơ Bản Nữ Nike Air Max 270",
      "color": "Xanh lá",
      "type": productTypes[4],
      "gender": "Female",
      "brand": brands[1],
      "image": productImages.find(image => image.productDetailId ===251),
      "productDetails": productDetails.filter(detail => detail.productId ===51),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 52,
      "name": "Giày Cơ Bản Nữ Nike Air Max 270",
      "color": "Trắng",
      "type": productTypes[4],
      "gender": "Female",
      "brand": brands[1],
      "image": productImages.find(image => image.productDetailId ===256),
      "productDetails": productDetails.filter(detail => detail.productId ===52),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 53,
      "name": "Giày Cơ Bản Nữ Nike Air Max 270",
      "color": "Đỏ",
      "type": productTypes[4],
      "gender": "Female",
      "brand": brands[1],
      "image": productImages.find(image => image.productDetailId ===261),
      "productDetails": productDetails.filter(detail => detail.productId ===53),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 54,
      "name": "Giày Cơ Bản Nữ Nike Air Max 270",
      "color": "Xám",
      "type": productTypes[4],
      "gender": "Female",
      "brand": brands[1],
      "image": productImages.find(image => image.productDetailId ===266),
      "productDetails": productDetails.filter(detail => detail.productId ===54),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 55,
      "name": "Giày Cơ Bản Nữ Nike Air Max 270",
      "color": "Xanh dương",
      "type": productTypes[4],
      "gender": "Female",
      "brand": brands[1],
      "image": productImages.find(image => image.productDetailId ===271),
      "productDetails": productDetails.filter(detail => detail.productId ===55),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 56,
      "name": "Giày Cơ Bản Nữ Nike Air Max 270",
      "color": "Đen",
      "type": productTypes[4],
      "gender": "Female",
      "brand": brands[1],
      "image": productImages.find(image => image.productDetailId ===276),
      "productDetails": productDetails.filter(detail => detail.productId ===56),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 57,
      "name": "Giày Cơ Bản Nữ Nike Air Max 270",
      "color": "Trắng",
      "type": productTypes[4],
      "gender": "Female",
      "brand": brands[1],
      "image": productImages.find(image => image.productDetailId ===281),
      "productDetails": productDetails.filter(detail => detail.productId ===57),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 58,
      "name": "Giày Cơ Bản Nữ Nike Air Max 270",
      "color": "Hồng",
      "type": productTypes[4],
      "gender": "Female",
      "brand": brands[1],
      "image": productImages.find(image => image.productDetailId ===286),
      "productDetails": productDetails.filter(detail => detail.productId ===58),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 59,
      "name": "Giày Cơ Bản Nữ Nike Air Max 270",
      "color": "Đen",
      "type": productTypes[4],
      "gender": "Female",
      "brand": brands[1],
      "image": productImages.find(image => image.productDetailId ===291),
      "productDetails": productDetails.filter(detail => detail.productId ===59),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 60,
      "name": "Giày Thể Thao Nữ Embrace",
      "color": "Xám",
      "type": productTypes[0],
      "gender": "Female",
      "brand": brands[0],
      "image": productImages.find(image => image.productDetailId ===296),
      "productDetails": productDetails.filter(detail => detail.productId ===60),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 61,
      "name": "Giày Thể Thao Nữ Embrace",
      "color": "Đen",
      "type": productTypes[0],
      "gender": "Female",
      "brand": brands[0],
      "image": productImages.find(image => image.productDetailId ===301),
      "productDetails": productDetails.filter(detail => detail.productId ===61),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 62,
      "name": "Giày Thể Thao Nữ Embrace",
      "color": "Hồng",
      "type": productTypes[0],
      "gender": "Female",
      "brand": brands[0],
      "image": productImages.find(image => image.productDetailId ===306),
      "productDetails": productDetails.filter(detail => detail.productId ===62),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 63,
      "name": "Giày Thể Thao Nữ Embrace Ver 2",
      "color": "Xanh dương",
      "type": productTypes[0],
      "gender": "Female",
      "brand": brands[0],
      "image": productImages.find(image => image.productDetailId ===311),
      "productDetails": productDetails.filter(detail => detail.productId ===63),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 64,
      "name": "Giày Thể Thao Nữ Embrace Ver 2",
      "color": "Xám",
      "type": productTypes[0],
      "gender": "Female",
      "brand": brands[0],
      "image": productImages.find(image => image.productDetailId ===316),
      "productDetails": productDetails.filter(detail => detail.productId ===64),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 65,
      "name": "Giày Thể Thao Nữ Embrace Ver 2",
      "color": "Hồng",
      "type": productTypes[0],
      "gender": "Female",
      "brand": brands[0],
      "image": productImages.find(image => image.productDetailId ===321),
      "productDetails": productDetails.filter(detail => detail.productId ===65),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 66,
      "name": "Giày Thể Thao Nữ Embrace Ver 2",
      "color": "Xanh lá cây",
      "type": productTypes[0],
      "gender": "Female",
      "brand": brands[0],
      "image": productImages.find(image => image.productDetailId ===326),
      "productDetails": productDetails.filter(detail => detail.productId ===66),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 67,
      "name": "Giày Búp Bê Nữ Biti’s Embrace",
      "color": "Hồng",
      "type": productTypes[6],
      "gender": "Female",
      "brand": brands[0],
      "image": productImages.find(image => image.productDetailId ===331),
      "productDetails": productDetails.filter(detail => detail.productId ===67),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 68,
      "name": "Giày Búp Bê Nữ Biti’s Embrace",
      "color": "Kem",
      "type": productTypes[5],
      "gender": "Female",
      "brand": brands[0],
      "image": productImages.find(image => image.productDetailId ===336),
      "productDetails": productDetails.filter(detail => detail.productId ===68),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 69,
      "name": "Giày Thời Trang Nữ Biti's",
      "color": "Xanh",
      "type": productTypes[6],
      "gender": "Female",
      "brand": brands[0],
      "image": productImages.find(image => image.productDetailId ===341),
      "productDetails": productDetails.filter(detail => detail.productId ===69),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 70,
      "name": "Giày Thời Trang Nữ Biti's",
      "color": "Đen",
      "type": productTypes[6],
      "gender": "Female",
      "brand": brands[0],
      "image": productImages.find(image => image.productDetailId ===346),
      "productDetails": productDetails.filter(detail => detail.productId ===70),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 71,
      "name": "Giày Thời Trang Nữ Gosto Sunweave",
      "color": "Nâu",
      "type": productTypes[6],
      "gender": "Female",
      "brand": brands[0],
      "image": productImages.find(image => image.productDetailId ===351),
      "productDetails": productDetails.filter(detail => detail.productId ===71),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 72,
      "name": "Giày Thời Trang Nữ Gosto Sunweave",
      "color": "Đen",
      "type": productTypes[6],
      "gender": "Female",
      "brand": brands[0],
      "image": productImages.find(image => image.productDetailId ===356),
      "productDetails": productDetails.filter(detail => detail.productId ===72),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 73,
      "name": "Giày Thời Trang Nữ Biti's",
      "color": "Đen",
      "type": productTypes[6],
      "gender": "Female",
      "brand": brands[0],
      "image": productImages.find(image => image.productDetailId ===361),
      "productDetails": productDetails.filter(detail => detail.productId ===73),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 74,
      "name": "Giày Thời Trang Nữ Biti's",
      "color": "Vàng",
      "type": productTypes[6],
      "gender": "Female",
      "brand": brands[0],
      "image": productImages.find(image => image.productDetailId ===366),
      "productDetails": productDetails.filter(detail => detail.productId ===74),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 75,
      "name": "Giày Thời Trang Nữ Biti's",
      "color": "Đen",
      "type": productTypes[6],
      "gender": "Female",
      "brand": brands[0],
      "image": productImages.find(image => image.productDetailId ===371),
      "productDetails": productDetails.filter(detail => detail.productId ===75),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 76,
      "name": "Giày Boots Nữ Cagole 90 mm",
      "color": "Xanh lá",
      "type": productTypes[7],
      "gender": "Female",
      "brand": brands[2],
      "image": productImages.find(image => image.productDetailId ===376),
      "productDetails": productDetails.filter(detail => detail.productId ===76),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 77,
      "name": "Giày Boots Nữ Cagole 90 mm",
      "color": "Đen",
      "type": productTypes[7],
      "gender": "Female",
      "brand": brands[2],
      "image": productImages.find(image => image.productDetailId ===381),
      "productDetails": productDetails.filter(detail => detail.productId ===77),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 78,
      "name": "Giày Boots Nữ Cagole 90 mm",
      "color": "Hồng",
      "type": productTypes[7],
      "gender": "Female",
      "brand": brands[2],
      "image": productImages.find(image => image.productDetailId ===386),
      "productDetails": productDetails.filter(detail => detail.productId ===78),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 79,
      "name": "Giày Boots Nữ Fetish 80 mm",
      "color": "Đen",
      "type": productTypes[7],
      "gender": "Female",
      "brand": brands[2],
      "image": productImages.find(image => image.productDetailId ===391),
      "productDetails": productDetails.filter(detail => detail.productId ===79),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 80,
      "name": "Giày Boots Nữ Crocs",
      "color": "Đen",
      "type": productTypes[7],
      "gender": "Female",
      "brand": brands[2],
      "image": productImages.find(image => image.productDetailId ===396),
      "productDetails": productDetails.filter(detail => detail.productId ===80),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 81,
      "name": "Giày Boots Nữ Crocs",
      "color": "Trắng",
      "type": productTypes[7],
      "gender": "Female",
      "brand": brands[2],
      "image": productImages.find(image => image.productDetailId ===401),
      "productDetails": productDetails.filter(detail => detail.productId ===81),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 82,
      "name": "Giày Boots Nữ Crocs",
      "color": "Xanh",
      "type": productTypes[7],
      "gender": "Female",
      "brand": brands[2],
      "image": productImages.find(image => image.productDetailId ===406),
      "productDetails": productDetails.filter(detail => detail.productId ===82),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 83,
      "name": "Giày Boots Nữ Crocs",
      "color": "Hồng",
      "type": productTypes[7],
      "gender": "Female",
      "brand": brands[2],
      "image": productImages.find(image => image.productDetailId ===411),
      "productDetails": productDetails.filter(detail => detail.productId ===83),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 84,
      "name": "Giày Boots Nữ Trooper Rupper",
      "color": "Xám",
      "type": productTypes[7],
      "gender": "Female",
      "brand": brands[2],
      "image": productImages.find(image => image.productDetailId ===416),
      "productDetails": productDetails.filter(detail => detail.productId ===84),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 85,
      "name": "Giày Boots Nữ Trooper Rupper",
      "color": "Đen",
      "type": productTypes[7],
      "gender": "Female",
      "brand": brands[2],
      "image": productImages.find(image => image.productDetailId ===421),
      "productDetails": productDetails.filter(detail => detail.productId ===85),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 86,
      "name": "Giày Boots Nữ Trooper Rupper",
      "color": "Nâu",
      "type": productTypes[7],
      "gender": "Female",
      "brand": brands[2],
      "image": productImages.find(image => image.productDetailId ===426),
      "productDetails": productDetails.filter(detail => detail.productId ===86),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 87,
      "name": "Giày Cơ Bản Nữ Nike Air Force 1 Fontanka",
      "color": "Xanh",
      "type": productTypes[4],
      "gender": "Female",
      "brand": brands[1],
      "image": productImages.find(image => image.productDetailId ===431),
      "productDetails": productDetails.filter(detail => detail.productId ===87),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 88,
      "name": "Giày Cơ Bản Nike Air Force 1 Fontanka",
      "color": "Cam ",
      "type": productTypes[4],
      "gender": "Female",
      "brand": brands[1],
      "image": productImages.find(image => image.productDetailId ===436),
      "productDetails": productDetails.filter(detail => detail.productId ===88),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 89,
      "name": "Giày Cơ Bản Nữ Nike Air Force 1 Fontanka",
      "color": "Trắng",
      "type": productTypes[4],
      "gender": "Female",
      "brand": brands[1],
      "image": productImages.find(image => image.productDetailId ===441),
      "productDetails": productDetails.filter(detail => detail.productId ===89),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 90,
      "name": "Giày Cơ Bản Nữ Nike Air Force 1 Fontanka",
      "color": "Hồng",
      "type": productTypes[4],
      "gender": "Female",
      "brand": brands[1],
      "image": productImages.find(image => image.productDetailId ===446),
      "productDetails": productDetails.filter(detail => detail.productId ===90),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 91,
      "name": "Giày Thể Thao Nữ Nike Air Zoom Pegasus",
      "color": "Xanh lá",
      "type": productTypes[0],
      "gender": "Female",
      "brand": brands[1],
      "image": productImages.find(image => image.productDetailId ===451),
      "productDetails": productDetails.filter(detail => detail.productId ===91),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 92,
      "name": "Giày Thể Thao Nữ Nike Air Zoom Pegasus",
      "color": "Đỏ",
      "type": productTypes[0],
      "gender": "Female",
      "brand": brands[1],
      "image": productImages.find(image => image.productDetailId ===456),
      "productDetails": productDetails.filter(detail => detail.productId ===92),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 93,
      "name": "Giày Thể Thao Nữ Nike Air Zoom Pegasus",
      "color": "Xám",
      "type": productTypes[0],
      "gender": "Female",
      "brand": brands[1],
      "image": productImages.find(image => image.productDetailId ===461),
      "productDetails": productDetails.filter(detail => detail.productId ===93),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 94,
      "name": "Giày Thể Thao Nữ Nike Air Zoom Victory More Uptempo",
      "color": "Xám",
      "type": productTypes[0],
      "gender": "Female",
      "brand": brands[1],
      "image": productImages.find(image => image.productDetailId ===466),
      "productDetails": productDetails.filter(detail => detail.productId ===94),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 95,
      "name": "Giày Thể Thao Nữ Nike Air Zoom LJ Elite",
      "color": "Xanh",
      "type": productTypes[0],
      "gender": "Female",
      "brand": brands[1],
      "image": productImages.find(image => image.productDetailId ===471),
      "productDetails": productDetails.filter(detail => detail.productId ===95),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 96,
      "name": "Giày Thể Thao Nữ Nike Air Zoom LJ Elite",
      "color": "Vàng",
      "type": productTypes[0],
      "gender": "Female",
      "brand": brands[1],
      "image": productImages.find(image => image.productDetailId ===476),
      "productDetails": productDetails.filter(detail => detail.productId ===96),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 97,
      "name": "Giày Sandal Nữ Nike EcoHaven Next Nature",
      "color": "Xanh",
      "type": productTypes[2],
      "gender": "Female",
      "brand": brands[1],
      "image": productImages.find(image => image.productDetailId ===481),
      "productDetails": productDetails.filter(detail => detail.productId ===97),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 98,
      "name": "Giày Sandal Nữ Nike EcoHaven Next Nature",
      "color": "Hồng",
      "type": productTypes[2],
      "gender": "Female",
      "brand": brands[1],
      "image": productImages.find(image => image.productDetailId ===486),
      "productDetails": productDetails.filter(detail => detail.productId ===98),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 99,
      "name": "Giày Sandal Nữ Nike Icon Classic",
      "color": "Hồng",
      "type": productTypes[2],
      "gender": "Female",
      "brand": brands[1],
      "image": productImages.find(image => image.productDetailId ===491),
      "productDetails": productDetails.filter(detail => detail.productId ===99),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    },
    {
      "id": 100,
      "name": "Giày Sandal Nữ Nike Icon Classic",
      "color": "Đen",
      "type": productTypes[2],
      "gender": "Female",
      "brand": brands[1],
      "image": productImages.find(image => image.productDetailId ===496),
      "productDetails": productDetails.filter(detail => detail.productId ===100),
      "description": "Đôi giày là phụ kiện thể hiện niềm đam mê và cá tính của người mang, với thiết kế thời trang, năng động, trẻ trung phù hợp với mọi lứa tuổi sẽ làm nổi bật lên cá tính, phong cách của bạn. Nhiều màu sắc, mẫu để lựa chọn làm mới phong cách hàng ngày. \nDo màn hình và điều kiện ánh sáng khác nhau, màu sắc thực tế của sản phẩm có thể chênh lệch khoảng 3-5%. \nFootwear luôn mong muốn mang lại trải nghiệm tốt nhất cho người dùng.",
      "active": true
    }
  ]

